[phases.setup]

[phases.install]
cmds = [
  "echo \"Authenticating with Docker Hub...\"",
  "echo $DOCKER_PASSWORD | docker login docker.io -u $DOCKER_USERNAME --password-stdin"
]

[start]
cmd = "docker run -p 3000:3000 -e WAHA_LICENSE_KEY=$WAHA_LICENSE_KEY devlikeapro/waha-plus:latest"
